moved headless command to playwirght config file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -45,7 +45,7 @@ jobs:
       - name: Enable Debug Mode
         run: echo "PWDEBUG=1" >> $GITHUB_ENV
       - name: Run UI tests
-        run: npx playwright test --grep "@ui" --headless || (echo "Playwright test failed!" && npx playwright show-trace && exit 1)
+        run: npx playwright test --grep "@ui" || (echo "Playwright test failed!" && npx playwright show-trace && exit 1)
       - uses: actions/upload-artifact@v4
         if: always()
         with:
